/*DBCC CHECKIDENT([Session], RESEED, 3)
DELETE FROM [Session] WHERE sessionId > 3
SELECT * FROM SESSION
SELECT * FROM [User]*/
/*UPDATE [Session] SET sessionEnd = GETDATE() WHERE sessionId = 1
/*EXEC START_SESSION @ROOMCODE = 'GD224', @SESSIONSTART = '2021-01-06 17:16:40.000', @SESSIONTYPE ='Class', @USERID = '103043778';*/ 